using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LuanVan.Migrations
{
    public partial class RenameAiHitlActionToAiNhatKyCanThiep : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
IF OBJECT_ID(N'dbo.AI_HITL_ACTION', N'U') IS NOT NULL
BEGIN
    IF OBJECT_ID(N'dbo.AI_HITL_ACTION_BAK', N'U') IS NULL
    BEGIN
        SELECT * INTO dbo.AI_HITL_ACTION_BAK FROM dbo.AI_HITL_ACTION;
    END
END
");

            migrationBuilder.Sql(@"
IF OBJECT_ID(N'dbo.AI_HITL_ACTION', N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.AI_NHATKY_CAN_THIEP', N'U') IS NULL
BEGIN
    EXEC sp_rename N'dbo.AI_HITL_ACTION', N'AI_NHATKY_CAN_THIEP';
END
");

            migrationBuilder.Sql(@"
IF OBJECT_ID(N'dbo.AI_NHATKY_CAN_THIEP', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','MACANTHIEP') IS NULL AND COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','MAHITL') IS NOT NULL
        EXEC sp_rename N'dbo.AI_NHATKY_CAN_THIEP.MAHITL', N'MACANTHIEP', N'COLUMN';
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','NGAY_CAN_THIEP') IS NULL AND COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','THOI_DIEM_DUYET') IS NOT NULL
        EXEC sp_rename N'dbo.AI_NHATKY_CAN_THIEP.THOI_DIEM_DUYET', N'NGAY_CAN_THIEP', N'COLUMN';
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','NGUOI_CANTHIEP') IS NULL AND COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','NGUOI_DUYET') IS NOT NULL
        EXEC sp_rename N'dbo.AI_NHATKY_CAN_THIEP.NGUOI_DUYET', N'NGUOI_CANTHIEP', N'COLUMN';
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','LY_DO') IS NULL AND COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','LYDO') IS NOT NULL
        EXEC sp_rename N'dbo.AI_NHATKY_CAN_THIEP.LYDO', N'LY_DO', N'COLUMN';
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','GIA_TRI_CU') IS NULL AND COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','OLD_VALUE') IS NOT NULL
        EXEC sp_rename N'dbo.AI_NHATKY_CAN_THIEP.OLD_VALUE', N'GIA_TRI_CU', N'COLUMN';
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','GIA_TRI_MOI') IS NULL AND COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','NEW_VALUE') IS NOT NULL
        EXEC sp_rename N'dbo.AI_NHATKY_CAN_THIEP.NEW_VALUE', N'GIA_TRI_MOI', N'COLUMN';
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','NGUON_CANTHIEP') IS NULL
        ALTER TABLE dbo.AI_NHATKY_CAN_THIEP ADD NGUON_CANTHIEP nvarchar(50) NULL;
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','ACTION_TYPE') IS NULL
        ALTER TABLE dbo.AI_NHATKY_CAN_THIEP ADD ACTION_TYPE nvarchar(50) NULL;
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','ACTION_SOURCE') IS NULL
        ALTER TABLE dbo.AI_NHATKY_CAN_THIEP ADD ACTION_SOURCE nvarchar(50) NULL;
END
");

            migrationBuilder.Sql(@"
IF OBJECT_ID(N'dbo.AI_HITL_ACTION', N'V') IS NOT NULL
    DROP VIEW dbo.AI_HITL_ACTION;
IF OBJECT_ID(N'dbo.AI_NHATKY_CAN_THIEP', N'U') IS NOT NULL
EXEC(N'
CREATE VIEW dbo.AI_HITL_ACTION
AS
SELECT
    MACANTHIEP AS MAHITL,
    MADANHGIA,
    MADUDOAN,
    MANHANVIEN,
    NGUOI_CANTHIEP AS NGUOI_DUYET,
    NGAY_CAN_THIEP AS THOI_DIEM_DUYET,
    SO_LAN_CHINH_SUA,
    LY_DO,
    GIA_TRI_CU,
    GIA_TRI_MOI,
    NGUON_CANTHIEP,
    ACTION_TYPE,
    ACTION_SOURCE
FROM dbo.AI_NHATKY_CAN_THIEP
');
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
IF OBJECT_ID(N'dbo.AI_HITL_ACTION', N'V') IS NOT NULL
    DROP VIEW dbo.AI_HITL_ACTION;
");

            migrationBuilder.Sql(@"
IF OBJECT_ID(N'dbo.AI_NHATKY_CAN_THIEP', N'U') IS NOT NULL
BEGIN
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','NGUOI_DUYET') IS NULL AND COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','NGUOI_CANTHIEP') IS NOT NULL
        EXEC sp_rename N'dbo.AI_NHATKY_CAN_THIEP.NGUOI_CANTHIEP', N'NGUOI_DUYET', N'COLUMN';
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','THOI_DIEM_DUYET') IS NULL AND COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','NGAY_CAN_THIEP') IS NOT NULL
        EXEC sp_rename N'dbo.AI_NHATKY_CAN_THIEP.NGAY_CAN_THIEP', N'THOI_DIEM_DUYET', N'COLUMN';
    IF COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','MAHITL') IS NULL AND COL_LENGTH('dbo.AI_NHATKY_CAN_THIEP','MACANTHIEP') IS NOT NULL
        EXEC sp_rename N'dbo.AI_NHATKY_CAN_THIEP.MACANTHIEP', N'MAHITL', N'COLUMN';
END
");

            migrationBuilder.Sql(@"
IF OBJECT_ID(N'dbo.AI_NHATKY_CAN_THIEP', N'U') IS NOT NULL
   AND OBJECT_ID(N'dbo.AI_HITL_ACTION', N'U') IS NULL
BEGIN
    EXEC sp_rename N'dbo.AI_NHATKY_CAN_THIEP', N'AI_HITL_ACTION';
END
");
        }
    }
}
