using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LuanVan.Migrations
{
    /// <inheritdoc />
    public partial class AddKpiProposalWorkflowAndAssignmentLifecycle : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
IF COL_LENGTH('KPI_PHONGBAN', 'IS_ACTIVE') IS NULL
    ALTER TABLE [KPI_PHONGBAN] ADD [IS_ACTIVE] bit NOT NULL CONSTRAINT [DF_KPI_PHONGBAN_IS_ACTIVE] DEFAULT CAST(1 AS bit);
IF COL_LENGTH('KPI_PHONGBAN', 'NGAYKETTHUC_APDUNG') IS NULL
    ALTER TABLE [KPI_PHONGBAN] ADD [NGAYKETTHUC_APDUNG] datetime2(0) NULL;

IF COL_LENGTH('KPI_NHOM', 'IS_ACTIVE') IS NULL
    ALTER TABLE [KPI_NHOM] ADD [IS_ACTIVE] bit NOT NULL CONSTRAINT [DF_KPI_NHOM_IS_ACTIVE] DEFAULT CAST(1 AS bit);
IF COL_LENGTH('KPI_NHOM', 'NGAYKETTHUC_APDUNG') IS NULL
    ALTER TABLE [KPI_NHOM] ADD [NGAYKETTHUC_APDUNG] datetime2(0) NULL;

IF COL_LENGTH('KPI_NHANVIEN', 'IS_ACTIVE') IS NULL
    ALTER TABLE [KPI_NHANVIEN] ADD [IS_ACTIVE] bit NOT NULL CONSTRAINT [DF_KPI_NHANVIEN_IS_ACTIVE] DEFAULT CAST(1 AS bit);
IF COL_LENGTH('KPI_NHANVIEN', 'NGAYKETTHUC_APDUNG') IS NULL
    ALTER TABLE [KPI_NHANVIEN] ADD [NGAYKETTHUC_APDUNG] datetime2(0) NULL;

IF COL_LENGTH('KPI_DUAN', 'IS_ACTIVE') IS NULL
    ALTER TABLE [KPI_DUAN] ADD [IS_ACTIVE] bit NOT NULL CONSTRAINT [DF_KPI_DUAN_IS_ACTIVE] DEFAULT CAST(1 AS bit);
IF COL_LENGTH('KPI_DUAN', 'NGAYKETTHUC_APDUNG') IS NULL
    ALTER TABLE [KPI_DUAN] ADD [NGAYKETTHUC_APDUNG] datetime2(0) NULL;
");

            migrationBuilder.Sql(@"
IF OBJECT_ID(N'[DE_XUAT_KPI]', N'U') IS NULL
BEGIN
    CREATE TABLE [DE_XUAT_KPI] (
        [MADEXUAT] int NOT NULL IDENTITY,
        [MAKPI] int NULL,
        [MALOAIKPI] int NULL,
        [NGUOIDE_XUAT] int NOT NULL,
        [NGUOIDUYET] int NULL,
        [NGUOICAPNHAT] int NULL,
        [LOAI_DEXUAT] nvarchar(50) NOT NULL,
        [MANHANVIEN_APDUNG] int NULL,
        [MANHOM_APDUNG] int NULL,
        [MAPHONGBAN_APDUNG] int NULL,
        [MADUAN_APDUNG] int NULL,
        [TU_NGAY] date NOT NULL,
        [DEN_NGAY] date NULL,
        [TRONGSO_DEXUAT] decimal(5,2) NOT NULL,
        [TENKPI_DEXUAT] nvarchar(150) NULL,
        [MOTA_KPI_DEXUAT] nvarchar(500) NULL,
        [LYDO] nvarchar(500) NULL,
        [TRANGTHAI] nvarchar(50) NOT NULL DEFAULT N'ChoDuyet',
        [PHANHOI_ADMIN] nvarchar(500) NULL,
        [GHI_CHU] nvarchar(300) NULL,
        [NGAYTAO] datetime2(0) NOT NULL DEFAULT (GETDATE()),
        [NGAYCAPNHAT] datetime2(0) NULL,
        [NGAYDUYET] datetime2(0) NULL,
        CONSTRAINT [PK_DE_XUAT_KPI] PRIMARY KEY ([MADEXUAT]),
        CONSTRAINT [CK_DE_XUAT_KPI_DOITUONG] CHECK ((CASE WHEN [MANHANVIEN_APDUNG] IS NULL THEN 0 ELSE 1 END + CASE WHEN [MANHOM_APDUNG] IS NULL THEN 0 ELSE 1 END + CASE WHEN [MAPHONGBAN_APDUNG] IS NULL THEN 0 ELSE 1 END + CASE WHEN [MADUAN_APDUNG] IS NULL THEN 0 ELSE 1 END) = 1),
        CONSTRAINT [CK_DE_XUAT_KPI_LOAI] CHECK ([LOAI_DEXUAT] IN (N'TaoMoiKPI',N'ApDungKPI',N'DieuChinhKPI',N'HuyApDungKPI')),
        CONSTRAINT [CK_DE_XUAT_KPI_THOIGIAN] CHECK ([DEN_NGAY] IS NULL OR [DEN_NGAY] >= [TU_NGAY]),
        CONSTRAINT [CK_DE_XUAT_KPI_TRANGTHAI] CHECK ([TRANGTHAI] IN (N'ChoDuyet',N'DaDuyet',N'TuChoi',N'CanChinhSua')),
        CONSTRAINT [CK_DE_XUAT_KPI_TRONGSO] CHECK ([TRONGSO_DEXUAT] >= 0 AND [TRONGSO_DEXUAT] <= 100),
        CONSTRAINT [FK_DE_XUAT_KPI_DANHMUCKPI] FOREIGN KEY ([MAKPI]) REFERENCES [DANHMUCKPI] ([MAKPI]) ON DELETE SET NULL,
        CONSTRAINT [FK_DE_XUAT_KPI_DUAN_APDUNG] FOREIGN KEY ([MADUAN_APDUNG]) REFERENCES [DUAN] ([MADUAN]) ON DELETE SET NULL,
        CONSTRAINT [FK_DE_XUAT_KPI_LOAIKPI] FOREIGN KEY ([MALOAIKPI]) REFERENCES [LOAIKPI] ([MALOAIKPI]) ON DELETE SET NULL,
        CONSTRAINT [FK_DE_XUAT_KPI_NGUOICAPNHAT] FOREIGN KEY ([NGUOICAPNHAT]) REFERENCES [NHANVIEN] ([MANHANVIEN]) ON DELETE SET NULL,
        CONSTRAINT [FK_DE_XUAT_KPI_NGUOIDE_XUAT] FOREIGN KEY ([NGUOIDE_XUAT]) REFERENCES [NHANVIEN] ([MANHANVIEN]) ON DELETE NO ACTION,
        CONSTRAINT [FK_DE_XUAT_KPI_NGUOIDUYET] FOREIGN KEY ([NGUOIDUYET]) REFERENCES [NHANVIEN] ([MANHANVIEN]) ON DELETE SET NULL,
        CONSTRAINT [FK_DE_XUAT_KPI_NHANVIEN_APDUNG] FOREIGN KEY ([MANHANVIEN_APDUNG]) REFERENCES [NHANVIEN] ([MANHANVIEN]) ON DELETE SET NULL,
        CONSTRAINT [FK_DE_XUAT_KPI_NHOM_APDUNG] FOREIGN KEY ([MANHOM_APDUNG]) REFERENCES [NHOM] ([MANHOM]) ON DELETE SET NULL,
        CONSTRAINT [FK_DE_XUAT_KPI_PHONGBAN_APDUNG] FOREIGN KEY ([MAPHONGBAN_APDUNG]) REFERENCES [PHONGBAN] ([MAPHONGBAN]) ON DELETE SET NULL
    );
END

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_DE_XUAT_KPI_MADUAN_APDUNG' AND object_id = OBJECT_ID(N'[DE_XUAT_KPI]'))
    CREATE INDEX [IX_DE_XUAT_KPI_MADUAN_APDUNG] ON [DE_XUAT_KPI]([MADUAN_APDUNG]);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_DE_XUAT_KPI_MAKPI' AND object_id = OBJECT_ID(N'[DE_XUAT_KPI]'))
    CREATE INDEX [IX_DE_XUAT_KPI_MAKPI] ON [DE_XUAT_KPI]([MAKPI]);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_DE_XUAT_KPI_MALOAIKPI' AND object_id = OBJECT_ID(N'[DE_XUAT_KPI]'))
    CREATE INDEX [IX_DE_XUAT_KPI_MALOAIKPI] ON [DE_XUAT_KPI]([MALOAIKPI]);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_DE_XUAT_KPI_MANHANVIEN_APDUNG' AND object_id = OBJECT_ID(N'[DE_XUAT_KPI]'))
    CREATE INDEX [IX_DE_XUAT_KPI_MANHANVIEN_APDUNG] ON [DE_XUAT_KPI]([MANHANVIEN_APDUNG]);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_DE_XUAT_KPI_MANHOM_APDUNG' AND object_id = OBJECT_ID(N'[DE_XUAT_KPI]'))
    CREATE INDEX [IX_DE_XUAT_KPI_MANHOM_APDUNG] ON [DE_XUAT_KPI]([MANHOM_APDUNG]);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_DE_XUAT_KPI_MAPHONGBAN_APDUNG' AND object_id = OBJECT_ID(N'[DE_XUAT_KPI]'))
    CREATE INDEX [IX_DE_XUAT_KPI_MAPHONGBAN_APDUNG] ON [DE_XUAT_KPI]([MAPHONGBAN_APDUNG]);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_DE_XUAT_KPI_NGUOICAPNHAT' AND object_id = OBJECT_ID(N'[DE_XUAT_KPI]'))
    CREATE INDEX [IX_DE_XUAT_KPI_NGUOICAPNHAT] ON [DE_XUAT_KPI]([NGUOICAPNHAT]);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_DE_XUAT_KPI_NGUOIDE_XUAT' AND object_id = OBJECT_ID(N'[DE_XUAT_KPI]'))
    CREATE INDEX [IX_DE_XUAT_KPI_NGUOIDE_XUAT] ON [DE_XUAT_KPI]([NGUOIDE_XUAT]);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_DE_XUAT_KPI_NGUOIDUYET' AND object_id = OBJECT_ID(N'[DE_XUAT_KPI]'))
    CREATE INDEX [IX_DE_XUAT_KPI_NGUOIDUYET] ON [DE_XUAT_KPI]([NGUOIDUYET]);
");

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
IF OBJECT_ID(N'[DE_XUAT_KPI]', N'U') IS NOT NULL
    DROP TABLE [DE_XUAT_KPI];
");

            migrationBuilder.DropColumn(
                name: "IS_ACTIVE",
                table: "KPI_PHONGBAN");

            migrationBuilder.DropColumn(
                name: "NGAYKETTHUC_APDUNG",
                table: "KPI_PHONGBAN");

            migrationBuilder.DropColumn(
                name: "IS_ACTIVE",
                table: "KPI_NHOM");

            migrationBuilder.DropColumn(
                name: "NGAYKETTHUC_APDUNG",
                table: "KPI_NHOM");

            migrationBuilder.DropColumn(
                name: "IS_ACTIVE",
                table: "KPI_NHANVIEN");

            migrationBuilder.DropColumn(
                name: "NGAYKETTHUC_APDUNG",
                table: "KPI_NHANVIEN");

            migrationBuilder.DropColumn(
                name: "IS_ACTIVE",
                table: "KPI_DUAN");

            migrationBuilder.DropColumn(
                name: "NGAYKETTHUC_APDUNG",
                table: "KPI_DUAN");
        }
    }
}
