// <auto-generated />
using System;
using LuanVan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuanVan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421142730_AddAiPredictionPipelinePersistence")]
    partial class AddAiPredictionPipelinePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuanVan.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_AspNetUsers_NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.BinhLuan", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MABINHLUAN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"));

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIEC");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYTAO");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("NOIDUNG");

                    b.HasKey("MaBinhLuan")
                        .HasName("PK_BINHLUAN");

                    b.HasIndex("MaCongViec");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("BINHLUAN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACHUCVU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCHUCVU");

                    b.HasKey("MaChucVu")
                        .HasName("PK_CHUCVU");

                    b.ToTable("CHUCVU", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.CongViec", b =>
                {
                    b.Property<int>("MaCongViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIEC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCongViec"));

                    b.Property<decimal?>("DiemCongViec")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DIEMCONGVIEC");

                    b.Property<DateTime?>("HanHoanThanh")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("HANHOANTHANH");

                    b.Property<int?>("MaCongViecCha")
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIECCHA");

                    b.Property<int>("MaDoKho")
                        .HasColumnType("int")
                        .HasColumnName("MADOKHO");

                    b.Property<int>("MaDoUuTien")
                        .HasColumnType("int")
                        .HasColumnName("MADOUUTIEN");

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int")
                        .HasColumnName("MADUAN");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("int")
                        .HasColumnName("MATRANGTHAI");

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MOTA");

                    b.Property<string>("TenCongViec")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCONGVIEC");

                    b.HasKey("MaCongViec")
                        .HasName("PK_CONGVIEC");

                    b.HasIndex("MaCongViecCha")
                        .HasDatabaseName("IX_CONGVIEC_MACONGVIECCHA");

                    b.HasIndex("MaDoKho")
                        .HasDatabaseName("IX_CONGVIEC_MADOKHO");

                    b.HasIndex("MaDoUuTien")
                        .HasDatabaseName("IX_CONGVIEC_MADOUUTIEN");

                    b.HasIndex("MaDuAn")
                        .HasDatabaseName("IX_CONGVIEC_MADUAN");

                    b.HasIndex("MaTrangThai")
                        .HasDatabaseName("IX_CONGVIEC_MATRANGTHAI");

                    b.ToTable("CONGVIEC", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.CongViecKyNang", b =>
                {
                    b.Property<int>("MaCongViec")
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIEC");

                    b.Property<int>("MaKyNang")
                        .HasColumnType("int")
                        .HasColumnName("MAKYNANG");

                    b.Property<int?>("CapDoYeuCau")
                        .HasColumnType("int")
                        .HasColumnName("CAPDO_YEUCAU");

                    b.Property<decimal?>("TrongSo")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("TRONGSO");

                    b.HasKey("MaCongViec", "MaKyNang")
                        .HasName("PK_CONGVIEC_KYNANG");

                    b.HasIndex("MaKyNang");

                    b.ToTable("CONGVIEC_KYNANG", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.CongViecTaiLieu", b =>
                {
                    b.Property<int>("MaCongViec")
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIEC");

                    b.Property<int>("MaTaiLieu")
                        .HasColumnType("int")
                        .HasColumnName("MATAILIEU");

                    b.HasKey("MaCongViec", "MaTaiLieu")
                        .HasName("PK_CONGVIEC_TAILIEU");

                    b.HasIndex("MaTaiLieu");

                    b.ToTable("CONGVIEC_TAILIEU", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.DanhMucKpi", b =>
                {
                    b.Property<int>("MaKpi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKPI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKpi"));

                    b.Property<int>("MaLoaiKpi")
                        .HasColumnType("int")
                        .HasColumnName("MALOAIKPI");

                    b.Property<string>("TenKpi")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENKPI");

                    b.Property<decimal?>("TrongSo")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("TRONGSO");

                    b.HasKey("MaKpi")
                        .HasName("PK_DANHMUCKPI");

                    b.HasIndex("MaLoaiKpi");

                    b.ToTable("DANHMUCKPI", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.DoKho", b =>
                {
                    b.Property<int>("MaDoKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADOKHO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDoKho"));

                    b.Property<string>("TenDoKho")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENDOKHO");

                    b.HasKey("MaDoKho")
                        .HasName("PK_DOKHO");

                    b.ToTable("DOKHO", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.DoUuTien", b =>
                {
                    b.Property<int>("MaDoUuTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADOUUTIEN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDoUuTien"));

                    b.Property<string>("TenDoUuTien")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENDOUUTIEN");

                    b.HasKey("MaDoUuTien")
                        .HasName("PK_DOUUTIEN");

                    b.ToTable("DOUUTIEN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.DuAn", b =>
                {
                    b.Property<int>("MaDuAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADUAN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDuAn"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MOTA");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYKETTHUC");

                    b.Property<string>("TenDuAn")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENDUAN");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("MaDuAn")
                        .HasName("PK_DUAN");

                    b.ToTable("DUAN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.DuAnNhanVien", b =>
                {
                    b.Property<int>("MaDuAn")
                        .HasColumnType("int")
                        .HasColumnName("MADUAN");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<DateTime?>("NgayRoi")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYROI");

                    b.Property<DateTime?>("NgayThamGia")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYTHAMGIA");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("TRANGTHAI");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("VAITRO");

                    b.HasKey("MaDuAn", "MaNhanVien")
                        .HasName("PK_DUAN_NHANVIEN");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DUAN_NHANVIEN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.DuAnNhom", b =>
                {
                    b.Property<int>("MaDuAn")
                        .HasColumnType("int")
                        .HasColumnName("MADUAN");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int")
                        .HasColumnName("MANHOM");

                    b.Property<DateTime?>("NgayThamGia")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYTHAMGIA");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("MaDuAn", "MaNhom")
                        .HasName("PK_DUAN_NHOM");

                    b.HasIndex("MaNhom");

                    b.ToTable("DUAN_NHOM", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.DuAnPhongBan", b =>
                {
                    b.Property<int>("MaDuAn")
                        .HasColumnType("int")
                        .HasColumnName("MADUAN");

                    b.Property<int>("MaPhongBan")
                        .HasColumnType("int")
                        .HasColumnName("MAPHONGBAN");

                    b.Property<DateTime?>("NgayThamGia")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYTHAMGIA");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("MaDuAn", "MaPhongBan")
                        .HasName("PK_DUAN_PHONGBAN");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("DUAN_PHONGBAN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.DuDoanAi", b =>
                {
                    b.Property<int>("MaDuDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADUDOAN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDuDoan"));

                    b.Property<string>("Actor")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ACTOR");

                    b.Property<string>("DeXuatCaiThien")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DEXUATCAITHIEN");

                    b.Property<decimal?>("DiemDuDoan")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DIEMDUDOAN");

                    b.Property<string>("GoiYNguonLuc")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("GOIYNGUONLUC");

                    b.Property<string>("InputData")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("INPUTDATA");

                    b.Property<int>("MaModel")
                        .HasColumnType("int")
                        .HasColumnName("MAMODEL");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODELNAME");

                    b.Property<string>("OutputData")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OUTPUTDATA");

                    b.Property<DateTime?>("ThoiGianDuDoan")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("THOIGIANDUDOAN");

                    b.Property<decimal?>("XacSuatTreHan")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("XACSUATTREHAN");

                    b.Property<int?>("nam")
                        .HasColumnType("int")
                        .HasColumnName("NAM");

                    b.Property<int?>("thang")
                        .HasColumnType("int")
                        .HasColumnName("THANG");

                    b.HasKey("MaDuDoan")
                        .HasName("PK_DUDOANAI");

                    b.HasIndex("MaModel");

                    b.HasIndex("MaNhanVien", "ModelName", "thang", "nam")
                        .IsUnique()
                        .HasDatabaseName("UQ_DUDOANAI_NV_MODEL_THANG_NAM")
                        .HasFilter("[MODELNAME] IS NOT NULL");

                    b.ToTable("DUDOANAI", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.DuLieuAi", b =>
                {
                    b.Property<int>("MaDuLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADULIEU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDuLieu"));

                    b.Property<decimal?>("KpiTrungBinh")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("KPITRUNGBINH");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<int?>("SoCongViecHoanThanh")
                        .HasColumnType("int")
                        .HasColumnName("SOCONGVIECHOANTHANH");

                    b.Property<int?>("SoCongViecTreHan")
                        .HasColumnType("int")
                        .HasColumnName("SOCONGVIECTREHAN");

                    b.Property<decimal?>("ThoiGianTrungBinh")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("THOIGIANTRUNGBINH");

                    b.HasKey("MaDuLieu")
                        .HasName("PK_DULIEUAI");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DULIEUAI", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.KetQuaKpi", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKETQUA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<decimal?>("DiemSo")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DIEMSO");

                    b.Property<int>("MaKpi")
                        .HasColumnType("int")
                        .HasColumnName("MAKPI");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<int?>("nam")
                        .HasColumnType("int")
                        .HasColumnName("NAM");

                    b.Property<int?>("thang")
                        .HasColumnType("int")
                        .HasColumnName("THANG");

                    b.HasKey("MaKetQua")
                        .HasName("PK_KETQUAKPI");

                    b.HasIndex("MaKpi");

                    b.HasIndex("MaNhanVien", "MaKpi", "thang", "nam")
                        .IsUnique()
                        .HasDatabaseName("UQ_KETQUAKPI_NV_KPI_THANG_NAM")
                        .HasFilter("[THANG] IS NOT NULL AND [NAM] IS NOT NULL");

                    b.ToTable("KETQUAKPI", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.KpiDuAn", b =>
                {
                    b.Property<int>("MaKpi")
                        .HasColumnType("int")
                        .HasColumnName("MAKPI");

                    b.Property<int>("MaDuAn")
                        .HasColumnType("int")
                        .HasColumnName("MADUAN");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("date")
                        .HasColumnName("DEN_NGAY");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("GHI_CHU");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("TRANGTHAI");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("date")
                        .HasColumnName("TU_NGAY");

                    b.HasKey("MaKpi", "MaDuAn")
                        .HasName("PK_KPI_DUAN");

                    b.HasIndex("MaDuAn");

                    b.ToTable("KPI_DUAN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.KpiNhanVien", b =>
                {
                    b.Property<int>("MaKpi")
                        .HasColumnType("int")
                        .HasColumnName("MAKPI");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("date")
                        .HasColumnName("DEN_NGAY");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("GHI_CHU");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("TRANGTHAI");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("date")
                        .HasColumnName("TU_NGAY");

                    b.HasKey("MaKpi", "MaNhanVien")
                        .HasName("PK_KPI_NHANVIEN");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("KPI_NHANVIEN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.KpiNhom", b =>
                {
                    b.Property<int>("MaKpi")
                        .HasColumnType("int")
                        .HasColumnName("MAKPI");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int")
                        .HasColumnName("MANHOM");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("date")
                        .HasColumnName("DEN_NGAY");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("GHI_CHU");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("TRANGTHAI");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("date")
                        .HasColumnName("TU_NGAY");

                    b.HasKey("MaKpi", "MaNhom")
                        .HasName("PK_KPI_NHOM");

                    b.HasIndex("MaNhom");

                    b.ToTable("KPI_NHOM", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.KpiPhongBan", b =>
                {
                    b.Property<int>("MaKpi")
                        .HasColumnType("int")
                        .HasColumnName("MAKPI");

                    b.Property<int>("MaPhongBan")
                        .HasColumnType("int")
                        .HasColumnName("MAPHONGBAN");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("date")
                        .HasColumnName("DEN_NGAY");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("GHI_CHU");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("TRANGTHAI");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("date")
                        .HasColumnName("TU_NGAY");

                    b.HasKey("MaKpi", "MaPhongBan")
                        .HasName("PK_KPI_PHONGBAN");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("KPI_PHONGBAN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.KyNang", b =>
                {
                    b.Property<int>("MaKyNang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKYNANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKyNang"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MOTA");

                    b.Property<string>("TenKyNang")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TENKYNANG");

                    b.HasKey("MaKyNang")
                        .HasName("PK_KYNANG");

                    b.ToTable("KYNANG", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.KyNangNhanVien", b =>
                {
                    b.Property<int>("MaKyNang")
                        .HasColumnType("int")
                        .HasColumnName("MAKYNANG");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<int?>("CapDo")
                        .HasColumnType("int")
                        .HasColumnName("CAPDO");

                    b.Property<int?>("SoDuAnDaDung")
                        .HasColumnType("int")
                        .HasColumnName("SODUANDADUNG");

                    b.HasKey("MaKyNang", "MaNhanVien")
                        .HasName("PK_KYNANGNHANVIEN");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("KYNANGNHANVIEN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.LichSuTrangThaiCongViec", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MALICHSU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIEC");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("THOIGIAN");

                    b.Property<int?>("TrangThaiCu")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAICU");

                    b.Property<int?>("TrangThaiMoi")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAIMOI");

                    b.HasKey("MaLichSu")
                        .HasName("PK_LICHSUTRANGTHAICONGVIEC");

                    b.HasIndex("MaCongViec");

                    b.ToTable("LICHSUTRANGTHAICONGVIEC", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.LoaiKpi", b =>
                {
                    b.Property<int>("MaLoaiKpi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MALOAIKPI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiKpi"));

                    b.Property<string>("TenLoaiKpi")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAIKPI");

                    b.HasKey("MaLoaiKpi")
                        .HasName("PK_LOAIKPI");

                    b.ToTable("LOAIKPI", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.LoaiThongBao", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MALOAI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("MaLoai")
                        .HasName("PK_LOAITHONGBAO");

                    b.ToTable("LOAITHONGBAO", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.MoHinhAi", b =>
                {
                    b.Property<int>("MaModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAMODEL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaModel"));

                    b.Property<DateTime?>("NgayTrain")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYTRAIN");

                    b.Property<string>("TenModel")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENMODEL");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VERSION");

                    b.HasKey("MaModel")
                        .HasName("PK_MOHINHAI");

                    b.ToTable("MOHINHAI", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.MoHinhDuLieuAi", b =>
                {
                    b.Property<int>("MaModel")
                        .HasColumnType("int")
                        .HasColumnName("MAMODEL");

                    b.Property<int>("MaDuLieu")
                        .HasColumnType("int")
                        .HasColumnName("MADULIEU");

                    b.Property<decimal?>("MetricChinh")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("METRIC_CHINH");

                    b.Property<string>("MucDich")
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MUC_DICH");

                    b.Property<DateTime?>("NgaySuDung")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAY_SU_DUNG");

                    b.HasKey("MaModel", "MaDuLieu")
                        .HasName("PK_MOHINH_DULIEUAI");

                    b.HasIndex("MaDuLieu");

                    b.ToTable("MOHINH_DULIEUAI", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("AspNetUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("AspNetUserId");

                    b.Property<string>("Cccd")
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOTEN");

                    b.Property<int?>("MaChucVu")
                        .HasColumnType("int")
                        .HasColumnName("MACHUCVU");

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("int")
                        .HasColumnName("MAPHONGBAN");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYSINH");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYVAOLAM");

                    b.Property<int?>("PhoMaPhongBan")
                        .HasColumnType("int")
                        .HasColumnName("PHO_MAPHONGBAN");

                    b.Property<string>("Sdt")
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("MaNhanVien")
                        .HasName("PK_NHANVIEN");

                    b.HasIndex("AspNetUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_NHANVIEN_AspNetUserId")
                        .HasFilter("[AspNetUserId] IS NOT NULL");

                    b.HasIndex("Cccd")
                        .IsUnique()
                        .HasDatabaseName("UX_NHANVIEN_CCCD")
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_NHANVIEN_EMAIL")
                        .HasFilter("[EMAIL] IS NOT NULL");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("PhoMaPhongBan");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.NhatKyCongViec", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANHATKY");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("GHICHU");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIEC");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYCAPNHAT");

                    b.Property<decimal?>("PhanTramHoanThanh")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PHANTRAMHOANTHANH");

                    b.HasKey("MaNhatKy")
                        .HasName("PK_NHATKYCONGVIEC");

                    b.HasIndex("MaCongViec");

                    b.ToTable("NHATKYCONGVIEC", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.NhatKyHoatDong", b =>
                {
                    b.Property<int>("MaNhatKyHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANHATKYHOATDONG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKyHoatDong"));

                    b.Property<string>("HanhDong")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("HANHDONG");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("THOIGIAN");

                    b.HasKey("MaNhatKyHoatDong")
                        .HasName("PK_NHATKYHOATDONG");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("NHATKYHOATDONG", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.Nhom", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANHOM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhom"));

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYTAO");

                    b.Property<string>("TenNhom")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENNHOM");

                    b.Property<int?>("TruongNhom")
                        .HasColumnType("int")
                        .HasColumnName("TRUONGNHOM");

                    b.HasKey("MaNhom")
                        .HasName("PK_NHOM");

                    b.HasIndex("TruongNhom");

                    b.ToTable("NHOM", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.PhanCongNhanVien", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAPHANCONG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIEC");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<DateTime?>("NgayBatDauDuKien")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYBATDAUDUKIEN");

                    b.Property<DateTime?>("NgayBatDauThucTe")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYBATDAUTHUCTE");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYGIAO");

                    b.Property<DateTime?>("NgayKetThucDuKien")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYKETTHUCDUKIEN");

                    b.Property<DateTime?>("NgayKetThucThucTe")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYKETTHUCTHUCTE");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("MaPhanCong")
                        .HasName("PK_PHANCONGNHANVIEN");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaCongViec", "MaNhanVien")
                        .IsUnique()
                        .HasDatabaseName("UQ_PHANCONGNHANVIEN_CV_NV");

                    b.ToTable("PHANCONGNHANVIEN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.PhanCongNhom", b =>
                {
                    b.Property<int>("MaCongViec")
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIEC");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int")
                        .HasColumnName("MANHOM");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYGIAO");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("MaCongViec", "MaNhom")
                        .HasName("PK_PHANCONGNHOM");

                    b.HasIndex("MaNhom");

                    b.ToTable("PHANCONGNHOM", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.PhanCongPhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .HasColumnType("int")
                        .HasColumnName("MAPHONGBAN");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIEC");

                    b.Property<DateTime?>("NgayPhanCong")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYPHANCONG");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("MaPhongBan", "MaCongViec")
                        .HasName("PK_PHANCONGPHONGBAN");

                    b.HasIndex("MaCongViec");

                    b.ToTable("PHANCONGPHONGBAN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAPHONGBAN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongBan"));

                    b.Property<int?>("MaTruongPhong")
                        .HasColumnType("int")
                        .HasColumnName("MATRUONGPHONG");

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MOTA");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENPHONGBAN");

                    b.HasKey("MaPhongBan")
                        .HasName("PK_PHONGBAN");

                    b.HasIndex("MaTruongPhong");

                    b.ToTable("PHONGBAN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.TaiLieu", b =>
                {
                    b.Property<int>("MaTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATAILIEU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiLieu"));

                    b.Property<string>("HuongDan")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("HUONGDAN");

                    b.Property<string>("TenTaiLieu")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENTAILIEU");

                    b.HasKey("MaTaiLieu")
                        .HasName("PK_TAILIEU");

                    b.ToTable("TAILIEU", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.ThanhVienNhom", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<int>("MaNhom")
                        .HasColumnType("int")
                        .HasColumnName("MANHOM");

                    b.Property<DateTime?>("NgayGiaNhap")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYGIANHAP");

                    b.Property<string>("VaiTroTrongNhom")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("VAITROTRONGNHOM");

                    b.HasKey("MaNhanVien", "MaNhom")
                        .HasName("PK_THANHVIENNHOM");

                    b.HasIndex("MaNhom");

                    b.ToTable("THANHVIENNHOM", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATHONGBAO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<int>("MaLoai")
                        .HasColumnType("int")
                        .HasColumnName("MALOAI");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("NOIDUNG");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("THOIGIAN");

                    b.HasKey("MaThongBao")
                        .HasName("PK_THONGBAO");

                    b.HasIndex("MaLoai");

                    b.ToTable("THONGBAO", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.ThongBaoNhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<int>("MaThongBao")
                        .HasColumnType("int")
                        .HasColumnName("MATHONGBAO");

                    b.Property<bool?>("DaDoc")
                        .HasColumnType("bit")
                        .HasColumnName("DADOC");

                    b.HasKey("MaNhanVien", "MaThongBao")
                        .HasName("PK_THONGBAO_NHANVIEN");

                    b.HasIndex("MaThongBao");

                    b.ToTable("THONGBAO_NHANVIEN", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.TienDoCongViec", b =>
                {
                    b.Property<string>("MaTienDo")
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("MATIENDO");

                    b.Property<int>("MaCongViec")
                        .HasColumnType("int")
                        .HasColumnName("MACONGVIEC");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("NGAYCAPNHAT");

                    b.Property<decimal?>("PhanTramHoanThanh")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PHANTRAMHOANTHANH");

                    b.Property<int?>("TrangThaiHienTai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAIHIENTAI");

                    b.HasKey("MaTienDo")
                        .HasName("PK_TIENDOCONGVIEC");

                    b.HasIndex("MaCongViec");

                    b.ToTable("TIENDOCONGVIEC", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.TrangThaiCongViec", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATRANGTHAI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("TenTrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENTRANGTHAI");

                    b.HasKey("MaTrangThai")
                        .HasName("PK_TRANGTHAICONGVIEC");

                    b.ToTable("TRANGTHAICONGVIEC", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LuanVan.Models.BinhLuan", b =>
                {
                    b.HasOne("LuanVan.Models.CongViec", "CongViec")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BINHLUAN_CONGVIEC");

                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BINHLUAN_NHANVIEN");

                    b.Navigation("CongViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LuanVan.Models.CongViec", b =>
                {
                    b.HasOne("LuanVan.Models.CongViec", "CongViecCha")
                        .WithMany("CongViecCon")
                        .HasForeignKey("MaCongViecCha")
                        .HasConstraintName("FK_CONGVIEC_CHA");

                    b.HasOne("LuanVan.Models.DoKho", "DoKho")
                        .WithMany("CongViecs")
                        .HasForeignKey("MaDoKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CONGVIEC_DOKHO");

                    b.HasOne("LuanVan.Models.DoUuTien", "DoUuTien")
                        .WithMany("CongViecs")
                        .HasForeignKey("MaDoUuTien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CONGVIEC_DOUUTIEN");

                    b.HasOne("LuanVan.Models.DuAn", "DuAn")
                        .WithMany("CongViecs")
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CONGVIEC_DUAN");

                    b.HasOne("LuanVan.Models.TrangThaiCongViec", "TrangThaiCongViec")
                        .WithMany("CongViecs")
                        .HasForeignKey("MaTrangThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CONGVIEC_TRANGTHAI");

                    b.Navigation("CongViecCha");

                    b.Navigation("DoKho");

                    b.Navigation("DoUuTien");

                    b.Navigation("DuAn");

                    b.Navigation("TrangThaiCongViec");
                });

            modelBuilder.Entity("LuanVan.Models.CongViecKyNang", b =>
                {
                    b.HasOne("LuanVan.Models.CongViec", "CongViec")
                        .WithMany("CongViecKyNangs")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CONGVIEC_KYNANG_CONGVIEC");

                    b.HasOne("LuanVan.Models.KyNang", "KyNang")
                        .WithMany("CongViecKyNangs")
                        .HasForeignKey("MaKyNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CONGVIEC_KYNANG_KYNANG");

                    b.Navigation("CongViec");

                    b.Navigation("KyNang");
                });

            modelBuilder.Entity("LuanVan.Models.CongViecTaiLieu", b =>
                {
                    b.HasOne("LuanVan.Models.CongViec", "CongViec")
                        .WithMany("CongViecTaiLieus")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CONGVIEC_TAILIEU_CONGVIEC");

                    b.HasOne("LuanVan.Models.TaiLieu", "TaiLieu")
                        .WithMany("CongViecTaiLieus")
                        .HasForeignKey("MaTaiLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CONGVIEC_TAILIEU_TAILIEU");

                    b.Navigation("CongViec");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("LuanVan.Models.DanhMucKpi", b =>
                {
                    b.HasOne("LuanVan.Models.LoaiKpi", "LoaiKpi")
                        .WithMany("DanhMucKpis")
                        .HasForeignKey("MaLoaiKpi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DANHMUCKPI_LOAIKPI");

                    b.Navigation("LoaiKpi");
                });

            modelBuilder.Entity("LuanVan.Models.DuAnNhanVien", b =>
                {
                    b.HasOne("LuanVan.Models.DuAn", "DuAn")
                        .WithMany("DuAnNhanViens")
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DUAN_NHANVIEN_DUAN");

                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("DuAnNhanViens")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DUAN_NHANVIEN_NHANVIEN");

                    b.Navigation("DuAn");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LuanVan.Models.DuAnNhom", b =>
                {
                    b.HasOne("LuanVan.Models.DuAn", "DuAn")
                        .WithMany("DuAnNhoms")
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DUAN_NHOM_DUAN");

                    b.HasOne("LuanVan.Models.Nhom", "Nhom")
                        .WithMany("DuAnNhoms")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DUAN_NHOM_NHOM");

                    b.Navigation("DuAn");

                    b.Navigation("Nhom");
                });

            modelBuilder.Entity("LuanVan.Models.DuAnPhongBan", b =>
                {
                    b.HasOne("LuanVan.Models.DuAn", "DuAn")
                        .WithMany("DuAnPhongBans")
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DUAN_PHONGBAN_DUAN");

                    b.HasOne("LuanVan.Models.PhongBan", "PhongBan")
                        .WithMany("DuAnPhongBans")
                        .HasForeignKey("MaPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DUAN_PHONGBAN_PHONGBAN");

                    b.Navigation("DuAn");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("LuanVan.Models.DuDoanAi", b =>
                {
                    b.HasOne("LuanVan.Models.MoHinhAi", "MoHinhAi")
                        .WithMany("DuDoanAis")
                        .HasForeignKey("MaModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DUDOANAI_MOHINHAI");

                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("DuDoanAis")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DUDOANAI_NHANVIEN");

                    b.Navigation("MoHinhAi");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LuanVan.Models.DuLieuAi", b =>
                {
                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("DuLieuAis")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DULIEUAI_NHANVIEN");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LuanVan.Models.KetQuaKpi", b =>
                {
                    b.HasOne("LuanVan.Models.DanhMucKpi", "DanhMucKpi")
                        .WithMany("KetQuaKpis")
                        .HasForeignKey("MaKpi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KETQUAKPI_DANHMUCKPI");

                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("KetQuaKpis")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KETQUAKPI_NHANVIEN");

                    b.Navigation("DanhMucKpi");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LuanVan.Models.KpiDuAn", b =>
                {
                    b.HasOne("LuanVan.Models.DuAn", "DuAn")
                        .WithMany("KpiDuAns")
                        .HasForeignKey("MaDuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KPI_DUAN_DUAN");

                    b.HasOne("LuanVan.Models.DanhMucKpi", "DanhMucKpi")
                        .WithMany("KpiDuAns")
                        .HasForeignKey("MaKpi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KPI_DUAN_DANHMUCKPI");

                    b.Navigation("DanhMucKpi");

                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("LuanVan.Models.KpiNhanVien", b =>
                {
                    b.HasOne("LuanVan.Models.DanhMucKpi", "DanhMucKpi")
                        .WithMany("KpiNhanViens")
                        .HasForeignKey("MaKpi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KPI_NHANVIEN_DANHMUCKPI");

                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("KpiNhanViens")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KPI_NHANVIEN_NHANVIEN");

                    b.Navigation("DanhMucKpi");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LuanVan.Models.KpiNhom", b =>
                {
                    b.HasOne("LuanVan.Models.DanhMucKpi", "DanhMucKpi")
                        .WithMany("KpiNhoms")
                        .HasForeignKey("MaKpi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KPI_NHOM_DANHMUCKPI");

                    b.HasOne("LuanVan.Models.Nhom", "Nhom")
                        .WithMany("KpiNhoms")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KPI_NHOM_NHOM");

                    b.Navigation("DanhMucKpi");

                    b.Navigation("Nhom");
                });

            modelBuilder.Entity("LuanVan.Models.KpiPhongBan", b =>
                {
                    b.HasOne("LuanVan.Models.DanhMucKpi", "DanhMucKpi")
                        .WithMany("KpiPhongBans")
                        .HasForeignKey("MaKpi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KPI_PHONGBAN_DANHMUCKPI");

                    b.HasOne("LuanVan.Models.PhongBan", "PhongBan")
                        .WithMany("KpiPhongBans")
                        .HasForeignKey("MaPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KPI_PHONGBAN_PHONGBAN");

                    b.Navigation("DanhMucKpi");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("LuanVan.Models.KyNangNhanVien", b =>
                {
                    b.HasOne("LuanVan.Models.KyNang", "KyNang")
                        .WithMany("KyNangNhanViens")
                        .HasForeignKey("MaKyNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KYNANGNHANVIEN_KYNANG");

                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("KyNangNhanViens")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KYNANGNHANVIEN_NHANVIEN");

                    b.Navigation("KyNang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LuanVan.Models.LichSuTrangThaiCongViec", b =>
                {
                    b.HasOne("LuanVan.Models.CongViec", "CongViec")
                        .WithMany("LichSuTrangThaiCongViecs")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LICHSUTRANGTHAICONGVIEC_CONGVIEC");

                    b.Navigation("CongViec");
                });

            modelBuilder.Entity("LuanVan.Models.MoHinhDuLieuAi", b =>
                {
                    b.HasOne("LuanVan.Models.DuLieuAi", "DuLieuAi")
                        .WithMany("MoHinhDuLieuAis")
                        .HasForeignKey("MaDuLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MOHINH_DULIEUAI_DULIEUAI");

                    b.HasOne("LuanVan.Models.MoHinhAi", "MoHinhAi")
                        .WithMany("MoHinhDuLieuAis")
                        .HasForeignKey("MaModel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MOHINH_DULIEUAI_MOHINHAI");

                    b.Navigation("DuLieuAi");

                    b.Navigation("MoHinhAi");
                });

            modelBuilder.Entity("LuanVan.Models.NhanVien", b =>
                {
                    b.HasOne("LuanVan.Data.ApplicationUser", "AspNetUser")
                        .WithOne("NhanVien")
                        .HasForeignKey("LuanVan.Models.NhanVien", "AspNetUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_NHANVIEN_AspNetUsers");

                    b.HasOne("LuanVan.Models.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_NHANVIEN_CHUCVU");

                    b.HasOne("LuanVan.Models.PhongBan", "PhongBanQuanLy")
                        .WithMany("NhanVienQuanLys")
                        .HasForeignKey("MaPhongBan")
                        .HasConstraintName("FK_NHANVIEN_PHONGBAN");

                    b.HasOne("LuanVan.Models.PhongBan", "PhongBanPhoTrach")
                        .WithMany("NhanVienPhoTrachs")
                        .HasForeignKey("PhoMaPhongBan")
                        .HasConstraintName("FK_NHANVIEN_PHO_PHONGBAN");

                    b.Navigation("AspNetUser");

                    b.Navigation("ChucVu");

                    b.Navigation("PhongBanPhoTrach");

                    b.Navigation("PhongBanQuanLy");
                });

            modelBuilder.Entity("LuanVan.Models.NhatKyCongViec", b =>
                {
                    b.HasOne("LuanVan.Models.CongViec", "CongViec")
                        .WithMany("NhatKyCongViecs")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NHATKYCONGVIEC_CONGVIEC");

                    b.Navigation("CongViec");
                });

            modelBuilder.Entity("LuanVan.Models.NhatKyHoatDong", b =>
                {
                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("NhatKyHoatDongs")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NHATKYHOATDONG_NHANVIEN");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LuanVan.Models.Nhom", b =>
                {
                    b.HasOne("LuanVan.Models.NhanVien", "NhanVienTruongNhom")
                        .WithMany("NhomTruongNhoms")
                        .HasForeignKey("TruongNhom")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_NHOM_TRUONGNHOM");

                    b.Navigation("NhanVienTruongNhom");
                });

            modelBuilder.Entity("LuanVan.Models.PhanCongNhanVien", b =>
                {
                    b.HasOne("LuanVan.Models.CongViec", "CongViec")
                        .WithMany("PhanCongNhanViens")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PHANCONGNHANVIEN_CONGVIEC");

                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("PhanCongNhanViens")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PHANCONGNHANVIEN_NHANVIEN");

                    b.Navigation("CongViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LuanVan.Models.PhanCongNhom", b =>
                {
                    b.HasOne("LuanVan.Models.CongViec", "CongViec")
                        .WithMany("PhanCongNhoms")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PHANCONGNHOM_CONGVIEC");

                    b.HasOne("LuanVan.Models.Nhom", "Nhom")
                        .WithMany("PhanCongNhoms")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PHANCONGNHOM_NHOM");

                    b.Navigation("CongViec");

                    b.Navigation("Nhom");
                });

            modelBuilder.Entity("LuanVan.Models.PhanCongPhongBan", b =>
                {
                    b.HasOne("LuanVan.Models.CongViec", "CongViec")
                        .WithMany("PhanCongPhongBans")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PHANCONGPHONGBAN_CONGVIEC");

                    b.HasOne("LuanVan.Models.PhongBan", "PhongBan")
                        .WithMany("PhanCongPhongBans")
                        .HasForeignKey("MaPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PHANCONGPHONGBAN_PHONGBAN");

                    b.Navigation("CongViec");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("LuanVan.Models.PhongBan", b =>
                {
                    b.HasOne("LuanVan.Models.NhanVien", "TruongPhong")
                        .WithMany("PhongBans")
                        .HasForeignKey("MaTruongPhong")
                        .HasConstraintName("FK_PHONGBAN_TRUONGPHONG");

                    b.Navigation("TruongPhong");
                });

            modelBuilder.Entity("LuanVan.Models.ThanhVienNhom", b =>
                {
                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("ThanhVienNhoms")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_THANHVIENNHOM_NHANVIEN");

                    b.HasOne("LuanVan.Models.Nhom", "Nhom")
                        .WithMany("ThanhVienNhoms")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_THANHVIENNHOM_NHOM");

                    b.Navigation("NhanVien");

                    b.Navigation("Nhom");
                });

            modelBuilder.Entity("LuanVan.Models.ThongBao", b =>
                {
                    b.HasOne("LuanVan.Models.LoaiThongBao", "LoaiThongBao")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_THONGBAO_LOAITHONGBAO");

                    b.Navigation("LoaiThongBao");
                });

            modelBuilder.Entity("LuanVan.Models.ThongBaoNhanVien", b =>
                {
                    b.HasOne("LuanVan.Models.NhanVien", "NhanVien")
                        .WithMany("ThongBaoNhanViens")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_THONGBAO_NHANVIEN_NHANVIEN");

                    b.HasOne("LuanVan.Models.ThongBao", "ThongBao")
                        .WithMany("ThongBaoNhanViens")
                        .HasForeignKey("MaThongBao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_THONGBAO_NHANVIEN_THONGBAO");

                    b.Navigation("NhanVien");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("LuanVan.Models.TienDoCongViec", b =>
                {
                    b.HasOne("LuanVan.Models.CongViec", "CongViec")
                        .WithMany("TienDoCongViecs")
                        .HasForeignKey("MaCongViec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TIENDOCONGVIEC_CONGVIEC");

                    b.Navigation("CongViec");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LuanVan.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LuanVan.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuanVan.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LuanVan.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuanVan.Data.ApplicationUser", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LuanVan.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("LuanVan.Models.CongViec", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("CongViecCon");

                    b.Navigation("CongViecKyNangs");

                    b.Navigation("CongViecTaiLieus");

                    b.Navigation("LichSuTrangThaiCongViecs");

                    b.Navigation("NhatKyCongViecs");

                    b.Navigation("PhanCongNhanViens");

                    b.Navigation("PhanCongNhoms");

                    b.Navigation("PhanCongPhongBans");

                    b.Navigation("TienDoCongViecs");
                });

            modelBuilder.Entity("LuanVan.Models.DanhMucKpi", b =>
                {
                    b.Navigation("KetQuaKpis");

                    b.Navigation("KpiDuAns");

                    b.Navigation("KpiNhanViens");

                    b.Navigation("KpiNhoms");

                    b.Navigation("KpiPhongBans");
                });

            modelBuilder.Entity("LuanVan.Models.DoKho", b =>
                {
                    b.Navigation("CongViecs");
                });

            modelBuilder.Entity("LuanVan.Models.DoUuTien", b =>
                {
                    b.Navigation("CongViecs");
                });

            modelBuilder.Entity("LuanVan.Models.DuAn", b =>
                {
                    b.Navigation("CongViecs");

                    b.Navigation("DuAnNhanViens");

                    b.Navigation("DuAnNhoms");

                    b.Navigation("DuAnPhongBans");

                    b.Navigation("KpiDuAns");
                });

            modelBuilder.Entity("LuanVan.Models.DuLieuAi", b =>
                {
                    b.Navigation("MoHinhDuLieuAis");
                });

            modelBuilder.Entity("LuanVan.Models.KyNang", b =>
                {
                    b.Navigation("CongViecKyNangs");

                    b.Navigation("KyNangNhanViens");
                });

            modelBuilder.Entity("LuanVan.Models.LoaiKpi", b =>
                {
                    b.Navigation("DanhMucKpis");
                });

            modelBuilder.Entity("LuanVan.Models.LoaiThongBao", b =>
                {
                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("LuanVan.Models.MoHinhAi", b =>
                {
                    b.Navigation("DuDoanAis");

                    b.Navigation("MoHinhDuLieuAis");
                });

            modelBuilder.Entity("LuanVan.Models.NhanVien", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("DuAnNhanViens");

                    b.Navigation("DuDoanAis");

                    b.Navigation("DuLieuAis");

                    b.Navigation("KetQuaKpis");

                    b.Navigation("KpiNhanViens");

                    b.Navigation("KyNangNhanViens");

                    b.Navigation("NhatKyHoatDongs");

                    b.Navigation("NhomTruongNhoms");

                    b.Navigation("PhanCongNhanViens");

                    b.Navigation("PhongBans");

                    b.Navigation("ThanhVienNhoms");

                    b.Navigation("ThongBaoNhanViens");
                });

            modelBuilder.Entity("LuanVan.Models.Nhom", b =>
                {
                    b.Navigation("DuAnNhoms");

                    b.Navigation("KpiNhoms");

                    b.Navigation("PhanCongNhoms");

                    b.Navigation("ThanhVienNhoms");
                });

            modelBuilder.Entity("LuanVan.Models.PhongBan", b =>
                {
                    b.Navigation("DuAnPhongBans");

                    b.Navigation("KpiPhongBans");

                    b.Navigation("NhanVienPhoTrachs");

                    b.Navigation("NhanVienQuanLys");

                    b.Navigation("PhanCongPhongBans");
                });

            modelBuilder.Entity("LuanVan.Models.TaiLieu", b =>
                {
                    b.Navigation("CongViecTaiLieus");
                });

            modelBuilder.Entity("LuanVan.Models.ThongBao", b =>
                {
                    b.Navigation("ThongBaoNhanViens");
                });

            modelBuilder.Entity("LuanVan.Models.TrangThaiCongViec", b =>
                {
                    b.Navigation("CongViecs");
                });
#pragma warning restore 612, 618
        }
    }
}
