// <auto-generated />
using System;
using LuanVan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuanVan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503_AddCongViecMissingColumns")]
    partial class AddCongViecMissingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a minimal designer snapshot - in production you would typically
            // auto-generate this or let EF Core do it
#pragma warning restore 612, 618
        }
    }
}
