-- Add approval columns to TIENDOCONGVIEC table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TIENDOCONGVIEC' AND COLUMN_NAME = 'TRANGTHAIPHEDUYET')
BEGIN
    ALTER TABLE TIENDOCONGVIEC ADD TRANGTHAIPHEDUYET NVARCHAR(50) DEFAULT 'Chờ duyệt';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TIENDOCONGVIEC' AND COLUMN_NAME = 'NGUOIPHEDUYET')
BEGIN
    ALTER TABLE TIENDOCONGVIEC ADD NGUOIPHEDUYET INT;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TIENDOCONGVIEC' AND COLUMN_NAME = 'NGAYPHEDUYET')
BEGIN
    ALTER TABLE TIENDOCONGVIEC ADD NGAYPHEDUYET DATETIME2;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TIENDOCONGVIEC' AND COLUMN_NAME = 'LYDOTUCHOI')
BEGIN
    ALTER TABLE TIENDOCONGVIEC ADD LYDOTUCHOI NVARCHAR(500);
END

-- Create index if it doesn't exist
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_TIENDOCONGVIEC_NGUOIPHEDUYET' AND object_id=OBJECT_ID('TIENDOCONGVIEC'))
BEGIN
    CREATE INDEX IX_TIENDOCONGVIEC_NGUOIPHEDUYET ON TIENDOCONGVIEC(NGUOIPHEDUYET);
END

-- Add foreign key if it doesn't exist
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='FK_TIENDOCONGVIEC_NHANVIEN' AND TABLE_NAME='TIENDOCONGVIEC')
BEGIN
    ALTER TABLE TIENDOCONGVIEC ADD CONSTRAINT FK_TIENDOCONGVIEC_NHANVIEN FOREIGN KEY (NGUOIPHEDUYET) REFERENCES NHANVIEN(MANHANVIEN) ON DELETE SET NULL;
END

-- Record the migration in __EFMigrationsHistory
INSERT INTO __EFMigrationsHistory (MigrationId, ProductVersion) VALUES ('20260511_AddProgressApprovalFields', '8.0.8')
